### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by ettmetal** [davidbailey00/notion-linux#13]
# Issue

When logging in to Notion via Google, the application fails to continue login after it has been handled by the browser.

# Details

## Expected behaviour

When clicking 'Continue with Google' during login, the application opens a browser for authentication, I can select / sign in to my Google account, then Notion will redirect to a link which is handled by the app, logging me in to my Notion account in the app.

## Experienced Behaviour

When clicking 'Continue with Google' during login, the application opens a browser and I am able to authenticate my account. Once authenticated, Notion redirects to an application link, which I am able to select to be opened by Notion. Opening the link with Notion does nothing, and when I switch back to the Notion window, the login page is still visible

# Info

- OS: Pop!_OS 20.04 LTS
- Browser: Firefox 81.0.2
- notion-deb-builder: [Notion 2.0.7+](https://github.com/davidbailey00/notion-deb-builder/releases/tag/v2.0.7x) (tried both win & mac variants)

# Requested change

As this is a wrapper (a very much appreciated one! 😁) I don't expect you to find a way to let the application support this, although it would be cool if the readme noted that Google login is not supported.

**Comment by Rgrable** [comment]
I've experienced this issue as well, though it isn't a blocker. Putting your gmail address in the email field and attempting to login that way will generate a login key that you can use to get into your account.

**Comment by ettmetal** [comment]
@Rgrable I'm not sure what you're describing here, could you expand on it a little? Which email field are you talking about, and how does one extract the key?

**Comment by Rgrable** [comment]
Hey @ettmetal sure, when you're presented with the login page, input the gmail address that you used for the SSO

![image](https://user-images.githubusercontent.com/3835376/97786270-b6f4a580-1b67-11eb-8624-9cdd09cefd35.png)

You'll receive a prompt for a login code that will be sent to that email, using that code will allow you to login to that account.

![image](https://user-images.githubusercontent.com/3835376/97786314-ed322500-1b67-11eb-9595-e24217260764.png)

Hope that helps!

**Comment by ettmetal** [comment]
Cool, I see what you meant now - thanks for the workaround, it worked for me

**Comment by vtenfys** [comment]
Thanks for reporting this @ettmetal! I've added a section to the readme linking to your comment @Rgrable, closing this now :)

**Comment by vtenfys** [comment]
Hello, as of [the latest release](https://github.com/davidbailey00/notion-deb-builder/releases/tag/v2.0.11-patch2) it's now possible to login using Google and Apple ID.
