### ISSUE TITLE
Notion fails to launch (cookies.json)

### ISSUE THREAD

**Issue by jrobinson-uk** [davidbailey00/notion-linux#14]
Hi

When I install and lunch I get the following error:
`2020-11-09 13:37:26.805] [info] Checking for update
[2020-11-09 13:37:26.857] [info] Error reading /home/james/.config/notion-desktop/cookies.json Error: ~/.config/notion-desktop/cookies.json: ENOENT: no such file `

The `notion-desktop` folder exists and contains other folders but not cookies.json

**Comment by vtenfys** [comment]
hmm can you try deleting the whole folder `~/.config/notion-desktop` and see if it gets recreated?

**Comment by jrobinson-uk** [comment]
It does get recreated but doesn't generate cookies.json

**Comment by jrobinson-uk** [comment]
It actually looks like the error is caused by the app not finding wget as somewhere it's hardcoded at `/usr/bin/wget` my system isn't FHS and wget exists elsewhere.

**Comment by jrobinson-uk** [comment]
I've made some progress but now get:
`Checking for update
22:28:26.811 › Error reading /home/james/.config/notion-desktop/assets.json Error: ENOENT: no such file or directory, open '/home/james/.config/notion-desktop/assets.json'
22:28:26.811 › Error reading /home/james/.config/notion-desktop/headers.json Error: ENOENT: no such file or directory, open '/home/james/.config/notion-desktop/headers.json'`

and 

`Error: Error: Cannot find channel "latest-linux.yml" update info: HttpError: 404 
"method: GET url: https://desktop-release.notion-static.com/latest-linux.yml?noCache=1emnhvrj2\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"`

**Comment by dchw** [comment]
@jrobinson-uk If you can run Docker and Earthly, you can probably make this work the way you want: https://github.com/davidbailey00/notion-deb-builder/pull/15

**Comment by jrobinson-uk** [comment]
I currently have it running via steam-run which seems to be providing a suitable enviroment

**Comment by OllieJT** [comment]
@jrobinson-uk Could you elaborate a little on your solution for others who have the same issue?

I've also a countered this issue with `cookies.json`

**Comment by jrobinson-uk** [comment]
I happen to have `steam` installed, which comes with a utility called `steam-run` which can wrap binaries in a FHS environment. Whatever it is doing, it is meeting some dependency of notion's that I seem to be missing

**Comment by vtenfys** [comment]
@OllieJT @jrobinson-uk Can you try the latest release and see if this is still an issue?

**Comment by vtenfys** [comment]
closing since this issue has gone stale, and is likely fixed with the latest releases and/or is an issue with an uncommon system configuration - let me know if this is still an issue
