### ISSUE TITLE
Is the menubar necessary?

### ISSUE THREAD

**Issue by claxonberlin** [davidbailey00/notion-linux#17]
I was wondering if the menubar is needed for some specific purpose. And if it bothers others as well. 

I think it's just one line of code to change this, but I'm still trying to get my new setup to work properly.

**Comment by haydn-jones** [comment]
There is a project called notion-enhancer that (along with many other things) removes the menu bar. Currently this installation method is not compatible with notion-enhancer, but I believe there is about to be a release VERY soon that will be compatible with notion-deb-builder. Feel free to check it out

https://github.com/notion-enhancer/notion-enhancer

**Comment by dragonwocky** [comment]
@haydn-jones @clausbertels and as of 10 minutes ago, notion-enhancer is compatible with notion-deb-builder.

it's probably best if notion-deb-builder sticks to just building the official version of the app. if you do want to hack it and gain more control and extra features, that's where the enhancer comes in (all features are configurable and enable/disable-able, + custom javascript and css can easily be inserted).

![image](https://user-images.githubusercontent.com/16874139/101230616-7f46c380-36fa-11eb-8fd5-4b8986c138fd.png)

**Comment by claxonberlin** [comment]
Perfect timing, I'd say. Thank you.

**Comment by vtenfys** [comment]
>  and as of 10 minutes ago, notion-enhancer is compatible with notion-deb-builder

nice!! out of curiosity, what changed to make this possible?

edit: [the answer to this question](https://github.com/davidbailey00/notion-deb-builder/pull/18#issuecomment-739317778)

**Comment by vtenfys** [comment]
closing since this issue is out-of-scope of the project (the goal is not to alter Notion other than applying functional patches) and this can be achieved with notion-enhancer
