### ISSUE TITLE
redirect does not work

### ISSUE THREAD

**Issue by thinkmadu** [davidbailey00/notion-linux#20]
for some reason, notion disconnected from my account and now I can't log in anymore.
my account is logged with google, but after granting access to notion, the redirect does not work and google account does not log.

**SYSTEM**
Ubuntu 20.10

**Comment by vtenfys** [comment]
Can you try logging in using your email address rather than Google login? Google login is not currently supported, as per the README.

**Comment by vtenfys** [comment]
Hello, as of [the latest release](https://github.com/davidbailey00/notion-deb-builder/releases/tag/v2.0.11-patch2) it's now possible to login using Google and Apple ID.
