### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by forgiveboo** [davidbailey00/notion-linux#22]
I downloaded the deb and installed it, but when I log in, I can't return to the notion from the browser. I click Open xdg-open and nothing happens. How should this be solved.

**Comment by vtenfys** [comment]
Please see [the _Google/Apple Login doesn't work; what can I do?_ section](https://github.com/davidbailey00/notion-deb-builder#googleapple-login-doesnt-work-what-can-i-do) in the README

> Google/Apple login is not supported. You can login using your email address instead, making sure to use the same email as your Google Account or Apple ID.

**Comment by forgiveboo** [comment]
> Please see [the _Google/Apple Login doesn't work; what can I do?_ section](https://github.com/davidbailey00/notion-deb-builder#googleapple-login-doesnt-work-what-can-i-do) in the README
> 
> > Google/Apple login is not supported. You can login using your email address instead, making sure to use the same email as your Google Account or Apple ID.

Thanks

**Comment by vtenfys** [comment]
Hello, as of [the latest release](https://github.com/davidbailey00/notion-deb-builder/releases/tag/v2.0.11-patch2) it's now possible to login using Google and Apple ID.
