### ISSUE TITLE
Checking for app update too often

### ISSUE THREAD

**Issue by ngirard** [davidbailey00/notion-linux#23]
Happy new year and thanks for your efforts !

I just give your package a first try, and from the console output it seems like Notion is checking for updates every minute or so:
```sh
18:06:42.508 › Checking for app update
18:06:42.733 › No app update available
18:07:42.793 › Checking for app update
18:07:43.012 › No app update available
18:08:43.071 › Checking for app update
18:08:43.471 › No app update available
18:09:43.532 › Checking for app update
18:09:43.917 › No app update available
18:10:43.979 › Checking for app update
18:10:44.339 › No app update available
18:11:44.398 › Checking for app update
18:15:42.449 › No app update available
```
This seems far too much to me.
Would you have any way of lowering it to e.g. once every few hours ? Or should it be reported upstream ?

Cheers

**Comment by vtenfys** [comment]
These logs are coming from the original Notion application and not something I have added, so yes this appears to be an upstream issue.

**Comment by ngirard** [comment]
Alright. I've reported it upstream by sending a chat message.
I'll report back here if it's solved.

**Comment by ngirard** [comment]
So here's the response I got:
> We currently don't have way to lower it down since we keep per-minute backups of our database, which allows us to restore a snapshot of any page in the past 35 days if you need it - everything is stored on AWS (US West - Oregon). And the backups are automatically spread across multiple regions for redundancy - you can reach out to us if you need help restoring something.

> Additionally, I'll make sure to share your feedback with our Engineering Team to consider your request in the future

I'll let you decide whether to close this issue ; I'm under the impression that the problem isn't about to be fixed...

**Comment by vtenfys** [comment]
Thanks, I'll close this since it's upstream-related.
