### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by capriciousduck** [davidbailey00/notion-linux#34]
What's the difference between the notion site that I use on Chome and this repo's notion? Is it the offline capability?

**Comment by vtenfys** [comment]
Notion's desktop app has partial offline functionality - that is, if you go offline while working, you can keep editing any pages you've visited during your session.

Other than that, and being a desktop app, the experience is largely the same as if you were using the web version, for the native `notion-desktop` package.

If you try the `notion-enhanced` package instead, you will find some additional features such as tabs and themes - see [notion-enhancer#features](https://github.com/notion-enhancer/notion-enhancer#features) for more information.
