### ISSUE TITLE
Ubuntu repo seems to be offline

### ISSUE THREAD

**Issue by powerverwirrt** [davidbailey00/notion-linux#39]
Hey,
first of all: Thank you for providing this Linux version of Notion and pre-built enhanced packages.

During a routine "sudo apt update", I noticed that I couldn't actually reach your notion-enhanced repo (incl. the translations as you can see in the screenshot). Going to your Gemfury page gave me several 404s. I removed your repo for now.

If you have the time, I would be very grateful to see this project be kept alive.

![210314_0120](https://user-images.githubusercontent.com/54581329/111053376-961c5500-8463-11eb-9047-db1eedbce5a1.png)

**Comment by vtenfys** [comment]
Please see: https://github.com/davidbailey00/notion-linux/issues/37#issuecomment-788388302

You can safely re-add the repo as these lines are informational only.
