### ISSUE TITLE
Ubuntu apt package repository is not working properly.

### ISSUE THREAD

**Issue by kimhongsu** [davidbailey00/notion-linux#40]
When I update apt package, I get this messages.
![image](https://user-images.githubusercontent.com/6312462/112104808-fc853e00-8bee-11eb-9475-7bb0ebfa7ac7.png)

cat /etc/apt/sources.list.d/notion-linux.list
`deb [trusted=yes] https://notion.davidbailey.codes/debs/ /`

**Comment by vtenfys** [comment]
This is outside of my control but is safe to ignore. See: https://github.com/davidbailey00/notion-linux/issues/37#issuecomment-788388302

**Comment by kimhongsu** [comment]
Oh. I missed out to check the closed issue.
Thanks for your comment!

**Comment by vtenfys** [comment]
You're welcome! I should probably put something in the readme now that a few people have asked this...
