### ISSUE TITLE
How to hide the menu bar on top ? is it possible ?

### ISSUE THREAD

**Issue by aahnik** [davidbailey00/notion-linux#41]
![image](https://user-images.githubusercontent.com/66209958/113378782-778be880-9395-11eb-8a64-739d67eba3af.png)

I am referring to the thing with [File Edit View Window Help]

**Comment by vtenfys** [comment]
You can use the `notion-enhanced` package instead of `notion-desktop` to hide the menubar.

Removing it from the vanilla version is unsupported, as the vanilla version mimics the Windows version as closely as possible.

**Comment by aahnik** [comment]
wow! thanks @davidbailey00 for answering.
