### ISSUE TITLE
Index files returned error 404

### ISSUE THREAD

**Issue by LucasDondo** [davidbailey00/notion-linux#44]
When I tried to install it (Ubuntu, Debian, Linux Mint procedure), it returned this (for both `notion-desktop` and `notion-enhancer`):
```
E: Failed to fetch https://notion.davidbailey.codes/debs/en  404  Not Found [IP: 34.224.179.39 443]
E: Failed to fetch https://notion.davidbailey.codes/debs/en_US  404  Not Found [IP: 34.224.179.39 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Edit: I'm sorry, I just saw this is explained [here](https://github.com/davidbailey00/notion-linux/releases/tag/gemfury). Although, maybe those steps could be in the installation instructions.

**Comment by mayankjobanputra** [comment]
I am facing the same issue. I am a new user and I have followed the following steps for Ubuntu:

`wget https://notion.davidbailey.codes/notion-linux.list`
`sudo mv notion-linux.list /etc/apt/sources.list.d/notion-linux.list`
`sudo apt update && sudo apt install notion-desktop`


and I am still getting the same error.

`E: Failed to fetch https://notion.davidbailey.codes/debs/en_IN  404  Not Found [IP: 34.206.8.7 443]`
`E: Failed to fetch https://notion.davidbailey.codes/debs/en  404  Not Found [IP: 34.206.8.7 443]`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`

Please help.

**Comment by vtenfys** [comment]
> Although, maybe those steps could be in the installation instructions.

@LucasDondo  This is at the top of the README file already to make existing users aware :)

New users do not have to follow these steps as the repository list file is already up-to-date now.

> ... and I am still getting the same error.

@mayankjobanputra If you are a new user then this is likely a separate issue.

Are you able to install the `notion-desktop` package regardless of the 404s? If so this looks like #37. If not please open a new issue.

**Comment by mayankjobanputra** [comment]
@davidbailey00 yes I am able to install regardless of the 404s. I removed the /etc/apt/sources.list.d/notion-linux.list and ran `apt update` to get rid of errors.
