### ISSUE TITLE
Disable spell check

### ISSUE THREAD

**Issue by jesuslencina** [davidbailey00/notion-linux#46]
I use Notion for taking notes in Spanish, but my OS is in English. Using this app, all the words are underlined in red, since they are not recognized as correct spelling (probably because it's spanish). I want to disable it, but I don't find any language or spell check settings within the app. Is there anything I can do? Thanks,

**Comment by vtenfys** [comment]
Hi, unfortunately there is not a way to do this - another user asked me this same question on Twitter and I tried to find a workaround but wasn't successful.

This is a general issue with the Notion app which occurs on Windows too - I do not usually fix these kinds of issues as they require further research and reverse engineering into how the application works. However, you may wish to open a feature request in [notion enhancer](https://github.com/notion-enhancer/notion-enhancer)
