### ISSUE TITLE
Notion Enhanced not working

### ISSUE THREAD

**Issue by ghost** [davidbailey00/notion-linux#52]
Notion Enhanced list does not work:
I've tried both:
```
wget https://notion.davidbailey.codes/notionenhanced.list
sudo mv notionenhanced.list /etc/apt/sources.list.d/notionenhanced.list
sudo apt update && sudo apt install notionenhanced
```

and

```
wget https://notion.davidbailey.codes/notion-enhanced.list
sudo mv notion-enhanced.list /etc/apt/sources.list.d/notion-enhanced.list
sudo apt update && sudo apt install notion-enhanced
```

but the links don't work. I get this error::

```
--2021-05-23 12:10:19--  https://notion.davidbailey.codes/notionenhanced.list
Resolving notion.davidbailey.codes (notion.davidbailey.codes)... 206.189.50.60, 159.65.118.56, 2a03:b0c0:3:d0::d23:e001, ...
Connecting to notion.davidbailey.codes (notion.davidbailey.codes)|206.189.50.60|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-23 12:10:19 ERROR 404: Not Found.
```

**Comment by ghost** [comment]
I forgot to add this. I did `apt search notion-enhanced` and it is in the **apt** option

```
sudo apt search notion-enhanced
Sorting... Done
Full Text Search... Done
notion-enhanced/unknown 2.0.11-8 amd64
  Notion desktop application Notion desktop application
```

Should we install it via **apt** or not?

**Comment by vtenfys** [comment]
Hey, it looks like you made a typo in your first set of commands, as a hyphen is required.

Run `sudo apt install notion-desktop` and you should be good to go.

> I did apt search notion-enhanced and it is in the apt option. Should we install it via apt or not?

I am not sure what you mean by this.

**Comment by ghost** [comment]
Yes, I tried it both ways (with and without the hyphen. But it didn't work either way.
What I meant was, in the [README.md](https://github.com/davidbailey00/notion-linux#install) it says `To install Notion with Notion Enhancer mods applied, replace notion-desktop with notion-enhanced` So I did so as you can see above in the open issue statement and it didn't work. I did run `sudo apt install notion-enhanced` and it installed but I don't think this is the correct way but it does install. It doesn't work properly though.

**Comment by vtenfys** [comment]
Ah, I see what has happened - you have replaced `notion-linux.list` with `notion-enhanced.list` in the commands. Note that you only need to replace "notion-desktop" with "notion-enhanced", but the repository URL is the same in both cases (`notion-linux.list`).

Please remove any of the incorrect repositories from `/etc/apt/sources.list.d` and run the following commands:

```sh
wget https://notion.davidbailey.codes/notion-linux.list
sudo mv notion-linux.list /etc/apt/sources.list.d/notion-linux.list
sudo apt update && sudo apt install notion-enhanced
```

**Comment by ghost** [comment]
OK, thanks for that. I misunderstood.

Thanks for the help and clarifying ;)
