### ISSUE TITLE
unable to resolve host address ‘notion.davidbailey.codes’

### ISSUE THREAD

**Issue by 0x61nas** [davidbailey00/notion-linux#57]
This message appears to me
`-2021-10-22 18:35:58-- https://notion.davidbailey.codes/notion-linux.list
Resolving notion.davidbailey.codes (notion.davidbailey.codes)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'notion.davidbailey.codes'
`
When I try to run this
`wget https://notion.davidbailey.codes/notion-linux.list`

**Comment by vtenfys** [comment]
This seems like a problem with your DNS resolver - try again later, or consider switching to [Google Public DNS](https://developers.google.com/speed/public-dns) if it's still not working.
