### ISSUE TITLE
Mac/Windows versions swapped?

### ISSUE THREAD

**Issue by agriffis** [davidbailey00/notion-linux#6]
It looks like the Mac and Windows versions are swapped somehow?

![image](https://user-images.githubusercontent.com/50637/73886108-f4c1d900-4836-11ea-9b7d-6948d65560d9.png)

**Comment by vtenfys** [comment]
Oops, you're right - just fixed! I named the assets the wrong way around - `2.0.7-win` was actually the Mac build, and vice versa.
